name: Docker Image CI

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: naadeemharis810  # Store your Docker Hub username as a GitHub secret
        password: f@st2013842  # Store your Docker Hub password as a GitHub secret

    # Build and push the Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: naadeemharis810/mlops_act2:latest  # Change this to your Docker Hub repo and image name

    # Verify the Docker image
    - name: Verify Docker image
      run: docker images
