name: Docker Image CI

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: harisnadeem471  # Docker Hub username stored in GitHub Secrets
          password: f@st2013842  # Docker Hub password stored in GitHub Secrets

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: harisnadeem471/mlops_act2:latest  # Docker Hub repository and image name

      # Verify the Docker image
      - name: Verify Docker image
        run: docker images
